export const CHECK_IF_MOBILE = 'CHECK_IF_MOBILE'

export const SET_CURRENT_VIEW = 'SET_CURRENT_VIEW'

export const SHOW_FOOTER = 'SHOW_FOOTER'

export const CAN_SCROLL = 'CAN_SCROLL'

export const DO_ANIMATION = 'DO_ANIMATION'

export const SET_FALLBACK_IMAGE = 'SET_FALLBACK_IMAGE'
